import Footer from './components/footer/Footer.jsx';
import Navbar from './components/navbar/Navbar.jsx';
import './globals.css';
import { Roboto } from 'next/font/google';

const inter = Roboto({ subsets: ['latin'], weight: '300' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
